# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  prefix: '[GIN-VUE-ADMIN]'
  director: 'log'
  link-name: 'latest_log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: false

jwt:
  expires-time: 24
  signing-key: 'fuck'

mysql:
  username: 'root'
  password: 'root123'
  host: '172.20.1.167'
  port: '3306'
  db-name: 'test1'
  config:
    - charset=utf8
    - parseTime=True
    - loc=Local